apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: actual-ai-secrets
  namespace: actual-ai
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "0c2d4a50-a13e-4c67-ba6d-d587dfe8c800"
        envSlug: "prod"
        secretsPath: "/actual-ai"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: actual-ai-env
    secretNamespace: actual-ai
