apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: accuripper
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZGVhZGZyb3N0dCIsInBhc3N3b3JkIjoiZ2hwX1JuRUlxa2twRnY0RjlRR2xBWVhPalhkNElMeE44dzM2VjNuWCIsImF1dGgiOiJaR1ZoWkdaeWIzTjBkRHBuYUhCZlVtNUZTWEZyYTNCR2RqUkdPVkZIYkVGWldFOXFXR1EwU1V4NFRqaDNNelpXTTI1WSJ9fX0=
