apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: mealie-secrets
  namespace: mealie
spec:
  hostAPI: https://__TAILSCALE_HOST__:8200/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "531805ba-6e35-43a6-8fc8-326ad2b6ce44"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: mealie-env
    secretNamespace: mealie
