apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: gatus-secrets
  namespace: gatus
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "8f8de143-3bdb-408a-9779-334ddb9c0c94"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: gatus-webhook
    secretNamespace: gatus
