apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cobalt-secrets
  namespace: cobalt
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "3acff490-0c4a-4eb1-bd75-65c02a3a7110"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: cobalt-env
    secretNamespace: cobalt
