apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cobalt
resources:
  - namespace.yaml
  - infisical-secret.yaml
  - rbac-tailscale.yaml
  - pvc-tailscale.yaml
  - configmap-haproxy.yaml
  - configmap-tailscale.yaml
  - cobalt-primary.yaml
  - cobalt-backup.yaml
  - cobalt-proxy.yaml
