apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-state
  namespace: cobalt
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
