apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "da3c1cc5-d234-4a20-8d69-bad0236654ba"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: vaultwarden-env
    secretNamespace: vaultwarden
