apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zipline-pg
  namespace: zipline
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6

  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: zipline
      owner: zipline
      secret:
        name: zipline-pg-app

  storage:
    size: 10Gi
    storageClass: local-path

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m

  monitoring:
    enablePodMonitor: false

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
