apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zipline-pg
  namespace: zipline
spec:
  inheritedMetadata:
    annotations:
      backup.velero.io/backup-volumes-excludes: pgdata
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6

  primaryUpdateStrategy: unsupervised

  bootstrap:
    recovery:
      source: zipline-pg-backup

  externalClusters:
  - name: zipline-pg-backup
    barmanObjectStore:
      destinationPath: "s3://k3s-backups-yeager/cnpg/zipline"
      endpointURL: "https://s3.us-east-005.backblazeb2.com"
      s3Credentials:
        accessKeyId:
          name: cnpg-b2-credentials
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-b2-credentials
          key: AWS_SECRET_ACCESS_KEY
      serverName: zipline-pg

  affinity:
    nodeSelector:
      kubernetes.io/hostname: yeager

  storage:
    size: 10Gi
    storageClass: local-path

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m

  monitoring:
    enablePodMonitor: false

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"

  backup:
    retentionPolicy: "14d"
    barmanObjectStore:
      serverName: zipline-pg-v2
      destinationPath: "s3://k3s-backups-yeager/cnpg/zipline"
      endpointURL: "https://s3.us-east-005.backblazeb2.com"
      s3Credentials:
        accessKeyId:
          name: cnpg-b2-credentials
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-b2-credentials
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
