apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: zipline-pg-app-secret
  namespace: zipline
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "1322db76-8f6a-4f64-a201-1be18959c7e3"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: zipline-pg-app
    secretNamespace: zipline
    secretType: kubernetes.io/basic-auth
    creationPolicy: Owner
    template:
      data:
        username: "zipline"
        password: "{{ .POSTGRESQL_PASSWORD.Value }}"
