apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: zipline-secrets
  namespace: zipline
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "1322db76-8f6a-4f64-a201-1be18959c7e3"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: zipline-env
    secretNamespace: zipline
