apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zipline
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - cnpg-networkpolicy.yaml
  - infisical-secret.yaml
  - cnpg-app-secret.yaml
  - cnpg-backup-secret.yaml
  - cnpg-cluster.yaml
  - cnpg-scheduledbackup.yaml
  - pvc.yaml
  - deployment.yaml
