apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zipline
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - infisical-secret.yaml
  - pvc.yaml
  - postgres.yaml
  - deployment.yaml
