apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: zipline
spec:
  replicas: 1
  serviceName: postgresql
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
      annotations:
        backup.velero.io/backup-volumes-excludes: pgdata
    spec:
      containers:
        - name: postgresql
          image: postgres:16@sha256:71e27bf60b70bded003791b5573f8b808365613f341df20ffcf0c1ed7bc13ddf
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: "zipline"
            - name: POSTGRES_DB
              value: "zipline"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zipline-env
                  key: POSTGRESQL_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "zipline"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "zipline"]
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: zipline-pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: zipline
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP
