apiVersion: v1
kind: ConfigMap
metadata:
  name: mas-config
  namespace: mas
data:
  config.yaml: |
    http:
      public_base: https://mas.pleasedontdmca.me/
      listeners:
        - name: web
          resources:
            - name: discovery
            - name: human
            - name: oauth
            - name: compat
            - name: graphql
            - name: assets
              path: /usr/local/share/mas-cli/assets/
            - name: health
          binds:
            - address: "[::]:8080"

    database:
      host: mas-pg-rw
      port: 5432
      username: mas
      password_file: /database-secret/password
      database: mas
      ssl_mode: disable

    secrets:
      encryption_file: /secrets/encryption-key
      keys:
        - key_file: /secrets/rsa_key

    passwords:
      enabled: true
      schemes:
        - version: 1
          algorithm: bcrypt
          unicode_normalization: true
        - version: 2
          algorithm: argon2id

    matrix:
      kind: synapse
      homeserver: pleasedontdmca.me
      endpoint: http://synapse.matrix.svc.cluster.local:8008
      secret_file: /secrets/matrix-secret

    upstream_oauth2:
      providers:
        - id: 01M3CM5DMBK0AMWKSWV22MKMQM
          synapse_idp_id: oidc-authentik
          issuer: https://sso.pleasedontdmca.me/application/o/matrix/
          human_name: Authentik
          client_id: e4rD5dUJFaQ5k7F3W0zaxrw0D2s98ZEqJLsrsghK
          client_secret_file: /secrets/authentik-client-secret
          token_endpoint_auth_method: client_secret_post
          scope: "openid profile email"
          fetch_userinfo: true
          claims_imports:
            localpart:
              action: require
              template: "{{ user.preferred_username }}"
            displayname:
              action: force
              template: "{{ user.name }}"
            email:
              action: force
              template: "{{ user.email }}"
