apiVersion: apps/v1
kind: Deployment
metadata:
  name: mas
  namespace: mas
spec:
  replicas: 0
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: mas
  template:
    metadata:
      labels:
        app: mas
    spec:
      containers:
        - name: mas
          image: ghcr.io/element-hq/matrix-authentication-service:latest@sha256:54f03be8ef26b9a6f2ab594d2a4c6e8074c3c09fbe05890a00ea50939d3e152a
          args:
            - server
            - --config
            - /config/config.yaml
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: secrets
              mountPath: /secrets
              readOnly: true
            - name: database-secret
              mountPath: /database-secret
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: mas-config
        - name: secrets
          secret:
            secretName: mas-secrets
        - name: database-secret
          secret:
            secretName: mas-pg-app
---
apiVersion: v1
kind: Service
metadata:
  name: mas
  namespace: mas
spec:
  selector:
    app: mas
  ports:
    - name: http
      port: 8080
      targetPort: http
