apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: mas-secrets
  namespace: mas
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "5cd176d5-af00-4aa0-a4c7-9fca63fcbeab"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: mas-secrets
    secretNamespace: mas
    secretType: Opaque
    creationPolicy: Owner
    template:
      data:
        encryption-key: "{{ .MAS_ENCRYPTION_KEY.Value }}"
        rsa_key: "{{ .MAS_RSA_KEY.Value }}"
        matrix-secret: "{{ .MAS_MATRIX_SECRET.Value }}"
        authentik-client-secret: "{{ .MAS_AUTHENTIK_CLIENT_SECRET.Value }}"
