apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mas
resources:
  - namespace.yaml
  - infisical-secret.yaml
  - cnpg-app-secret.yaml
  - cnpg-backup-secret.yaml
  - cnpg-cluster.yaml
  - cnpg-scheduledbackup.yaml
  - configmap.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - limitrange.yaml
