apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-matrix-auth-proxy
  namespace: matrix
spec:
  podSelector:
    matchLabels:
      app: matrix-auth-proxy
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: synapse
      ports:
        - protocol: TCP
          port: 8008
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: mas
          podSelector:
            matchLabels:
              app: mas
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
