apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: matrix-pg-app-secret
  namespace: matrix
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "5cd176d5-af00-4aa0-a4c7-9fca63fcbeab"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: matrix-pg-app
    secretNamespace: matrix
    secretType: kubernetes.io/basic-auth
    creationPolicy: Owner
    template:
      data:
        username: "synapse"
        password: "{{ .POSTGRES_PASSWORD.Value }}"
