apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: matrix-cnpg-backup-secrets
  namespace: matrix
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "976591a3-db8a-4be1-b388-318cded28abe"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedKubeSecretReferences:
    - secretName: cnpg-b2-credentials
      secretNamespace: matrix
      secretType: Opaque
      creationPolicy: Orphan
      template:
        includeAllSecrets: false
        data:
          AWS_ACCESS_KEY_ID: "{{ .B2_KEY_ID.Value }}"
          AWS_SECRET_ACCESS_KEY: "{{ .B2_APPLICATION_KEY.Value }}"
