apiVersion: v1
kind: ConfigMap
metadata:
  name: element-config
  namespace: matrix
data:
  element-config.json.tmpl: |
    {
      "default_server_config": {
        "m.homeserver": {
          "base_url": "${MATRIX_BASE_URL}",
          "server_name": "${MATRIX_SERVER_NAME}"
        },
        "m.identity_server": {
          "base_url": "https://vector.im"
        }
      },
      "brand": "Element",
      "integrations_ui_url": "https://scalar.vector.im/",
      "integrations_rest_url": "https://scalar.vector.im/api",
      "bug_report_endpoint_url": "https://element.io/bugreports/submit",
      "roomDirectory": {
        "servers": ["matrix.org"]
      },
      "element_call": {
        "url": "https://call.element.io",
        "use_exclusively": true
      },
      "features": {
        "feature_group_calls": true,
        "feature_video_rooms": true,
        "feature_element_call_video_rooms": true
      }
    }
