apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - cnpg-networkpolicy.yaml
  - infisical-secret.yaml
  - cnpg-app-secret.yaml
  - cnpg-backup-secret.yaml
  - cnpg-cluster.yaml
  - cnpg-scheduledbackup.yaml
  - pvc.yaml
  - synapse.yaml
  - element-configmap.yaml
  - element.yaml
  - synapse-admin.yaml
