apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: authentik-pg-app-secret
  namespace: authentik
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "ffb4a63e-d3dc-4c22-984e-871103f80eba"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: authentik-pg-app
    secretNamespace: authentik
    secretType: kubernetes.io/basic-auth
    creationPolicy: Owner
    template:
      data:
        username: "{{ .PG_USER.Value }}"
        password: "{{ .PG_PASS.Value }}"
