apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "ffb4a63e-d3dc-4c22-984e-871103f80eba"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: authentik-env
    secretNamespace: authentik
