apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - cnpg-networkpolicy.yaml
  - infisical-secret.yaml
  - cnpg-app-secret.yaml
  - cnpg-cluster.yaml
  - pvc.yaml
  - postgres.yaml
  - server.yaml
  - worker.yaml
  - rac.yaml
