apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: authentik
spec:
  replicas: 1
  serviceName: postgresql
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:17-alpine@sha256:742f40ea20b9ff2ff31db5458d127452988a2164df9e17441e191f3b72252193
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: PG_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: PG_PASS
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: PG_DB
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "100m"
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: authentik-pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: authentik
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP
