apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-server
  namespace: authentik
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: authentik-server
  template:
    metadata:
      labels:
        app: authentik-server
      annotations:
        backup.velero.io/backup-volumes-excludes: templates
    spec:
      containers:
        - name: server
          image: ghcr.io/goauthentik/server:2026.8.1@sha256:9d605ed569ff9f39146be39da93714b2acf19072acc4ab0f0e2f2d81be88cdce
          args: ["server"]
          ports:
            - containerPort: 9000
              name: http
            - containerPort: 9443
              name: https
          env:
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: "authentik-pg-rw"
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: AUTHENTIK_SECRET_KEY
            - name: AUTHENTIK_POSTGRESQL__USER
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: PG_USER
            - name: AUTHENTIK_POSTGRESQL__NAME
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: PG_DB
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: PG_PASS
            - name: AUTHENTIK_REDIS__DB
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: AUTHENTIK_REDIS__DB
            - name: AUTHENTIK_EMAIL__HOST
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: AUTHENTIK_EMAIL__HOST
            - name: AUTHENTIK_EMAIL__PORT
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: AUTHENTIK_EMAIL__PORT
            - name: AUTHENTIK_EMAIL__USERNAME
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: AUTHENTIK_EMAIL__USERNAME
            - name: AUTHENTIK_EMAIL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: AUTHENTIK_EMAIL__PASSWORD
            - name: AUTHENTIK_EMAIL__FROM
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: AUTHENTIK_EMAIL__FROM
            - name: AUTHENTIK_EMAIL__USE_TLS
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: AUTHENTIK_EMAIL__USE_TLS
            - name: AUTHENTIK_EMAIL__USE_SSL
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: AUTHENTIK_EMAIL__USE_SSL
          volumeMounts:
            - name: media
              mountPath: /media
            - name: templates
              mountPath: /templates
          readinessProbe:
            httpGet:
              path: /-/health/ready/
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /-/health/live/
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            limits:
              memory: "1280Mi"
              cpu: "750m"
            requests:
              memory: "512Mi"
              cpu: "100m"
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: authentik-media
        - name: templates
          persistentVolumeClaim:
            claimName: authentik-templates
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-server
  namespace: authentik
spec:
  type: NodePort
  selector:
    app: authentik-server
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 30900
