---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airpipe
  namespace: airpipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airpipe
  template:
    metadata:
      labels:
        app: airpipe
    spec:
      containers:
        - name: airpipe
          image: ghcr.io/sanyam-g/airpipe-relay:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "64Mi"
              cpu: "50m"

--- 

apiVersion: v1
kind: Service
metadata:
  name: airpipe
  namespace: airpipe
spec:
  type: NodePort
  selector:
    app: airpipe
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30124