apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cnpg-ingress
  namespace: infisical
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: infisical-pg
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: infisical
      ports:
        - protocol: TCP
          port: 5432
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cnpg-system
    - from:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: infisical-pg
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cnpg-egress
  namespace: infisical
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: infisical-pg
  policyTypes:
    - Egress
  egress:
    - {}
