apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-edge
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-edge
  template:
    metadata:
      labels:
        app: cloudflared-edge
    spec:
      nodeSelector:
        homelab.dev/node-class: edge
      tolerations:
        - key: homelab.dev/edge
          operator: Equal
          value: "true"
          effect: NoSchedule
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest@sha256:072c067d25ccbe61d46e18f0d0723255f2bb5304f7317caa95b27031520ff92c
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - $(TUNNEL_TOKEN)
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-edge-env
                  key: TUNNEL_TOKEN
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "32Mi"
              cpu: "50m"
