apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflared-secrets
  namespace: cloudflared
spec:
  hostAPI: https://__TAILSCALE_HOST__:8200/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "98299b05-ccf1-4280-8bf9-b786cf4dd9b7"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: cloudflared-env
    secretNamespace: cloudflared
