apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: couch-db-secrets
  namespace: couch-db
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "602a8f1b-d20e-427a-9cdb-84b9473990ea"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: couch-db-env
    secretNamespace: couch-db
