apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data
  namespace: couch-db
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-config
  namespace: couch-db
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
