apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-agent-data
  namespace: beszel-agent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
