apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: beszel-agent-secrets
  namespace: beszel-agent
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "84e0110e-a437-4df4-a40b-5c10cf2ac2a5"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: beszel-agent-env
    secretNamespace: beszel-agent
