apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: velero-secrets
  namespace: velero
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "976591a3-db8a-4be1-b388-318cded28abe"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedKubeSecretReferences:
    - secretName: velero-b2-env
      secretNamespace: velero
      secretType: Opaque
      creationPolicy: Orphan
      template:
        includeAllSecrets: true
    - secretName: velero-cloud-credentials
      secretNamespace: velero
      secretType: Opaque
      creationPolicy: Orphan
      template:
        includeAllSecrets: false
        data:
          cloud: |
            [default]
            aws_access_key_id={{ .B2_KEY_ID.Value }}
            aws_secret_access_key={{ .B2_APPLICATION_KEY.Value }}
