apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel
  namespace: pelican
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: panel
  template:
    metadata:
      labels:
        app: panel
    spec:
      containers:
        - name: panel
          image: ghcr.io/pelican-dev/panel:latest@sha256:3bc82ac43ae3a8e2e4b606a158a2a02bacc73d6210fd923cc1f59eda9529b381
          ports:
            - containerPort: 80
              name: http
          env:
            - name: XDG_DATA_HOME
              value: /pelican-data
            - name: APP_URL
              value: "https://panel.deadfrost.dev"
            - name: ASSET_URL
              value: "https://panel.deadfrost.dev"
            - name: BEHIND_PROXY
              value: "true"
            - name: TRUSTED_PROXIES
              value: "0.0.0.0/0,::/0"
            - name: ADMIN_EMAIL
              value: "__ADMIN_EMAIL__"
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "false"
          envFrom:
            - secretRef:
                name: pelican-env
          volumeMounts:
            - name: data
              mountPath: /pelican-data
            - name: logs
              mountPath: /var/www/html/storage/logs
          livenessProbe:
            httpGet:
              path: /up
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /up
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            limits:
              memory: "1Gi"
              cpu: "750m"
            requests:
              memory: "128Mi"
              cpu: "50m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pelican-data
        - name: logs
          persistentVolumeClaim:
            claimName: pelican-logs
---
apiVersion: v1
kind: Service
metadata:
  name: panel
  namespace: pelican
spec:
  type: NodePort
  selector:
    app: panel
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30180
