apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: pelican-secrets
  namespace: pelican
spec:
  hostAPI: https://__TAILSCALE_HOST__:8200/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "4524857e-b55e-44f1-861a-2cf140c9be09"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: pelican-env
    secretNamespace: pelican
