apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flaresolverr-config
  namespace: flaresolverr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
