apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: matrix-livekit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      hostname: auth-server
      containers:
        - name: auth-service
          image: ghcr.io/element-hq/lk-jwt-service:latest@sha256:29918567e6b7cd920e2853b4cd6848ce01b79947c3d19a9f1ed5b74f0a2a88bf
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: LIVEKIT_JWT_BIND
              value: ":8080"
            - name: LIVEKIT_URL
              value: "wss://matrixrtc.pleasedontdmca.me/livekit/sfu"
            - name: LIVEKIT_FULL_ACCESS_HOMESERVERS
              value: "pleasedontdmca.me"
            - name: LIVEKIT_KEY
              valueFrom:
                secretKeyRef:
                  name: matrix-livekit-env
                  key: LIVEKIT_KEY
            - name: LIVEKIT_SECRET
              valueFrom:
                secretKeyRef:
                  name: matrix-livekit-env
                  key: LIVEKIT_SECRET
          volumeMounts:
            - name: ca-certs
              mountPath: /etc/ssl/certs
              readOnly: true
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "32Mi"
              cpu: "25m"
      volumes:
        - name: ca-certs
          hostPath:
            path: /etc/ssl/certs
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: matrix-livekit
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30070
