apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: matrix-livekit-secrets
  namespace: matrix-livekit
spec:
  hostAPI: https://__TAILSCALE_HOST__:8200/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "ae8e9e22-047f-4534-9477-a28373fb97ec"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: matrix-livekit-env
    secretNamespace: matrix-livekit
