apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit
  namespace: matrix-livekit
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: livekit
  template:
    metadata:
      labels:
        app: livekit
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: yeager
      containers:
        - name: livekit
          image: livekit/livekit-server:latest@sha256:100b9a870616d02f5e3795b34e0b593b5054a26f8131a94fd3fa322ed3154b16
          args: ["--config", "/etc/livekit.yaml"]
          volumeMounts:
            - name: config
              mountPath: /etc/livekit.yaml
              subPath: config.yaml
              readOnly: true
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: config
          hostPath:
            path: /home/ubuntu/docker-compose/matrix/livekit
            type: Directory
