apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: poke-gate-secrets
  namespace: poke-gate
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectId: "859b5993-8f6e-460a-bb42-b297ff8d2be9"
        envSlug: "prod"
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: poke-gate-env
    secretNamespace: poke-gate
